### ISSUE TITLE
Typo may cause database name to be ignored

### ISSUE THREAD

**Issue by TheMonkWhoSoldHisServer** [alan-cooney/knex-data-api-client#1]
https://github.com/alan-cooney/knex-data-api-client/blob/master/index.js#L55

self.client.connectionSettings.data**b**ase - there's a "b" missing

**Comment by alan-cooney** [comment]
Thanks @benariamir - that's fixed now

**Comment by TheMonkWhoSoldHisServer** [comment]
Thank you !
