### ISSUE TITLE
Getting only 'timeout error' on failed exeuctions

### ISSUE THREAD

**Issue by TheMonkWhoSoldHisServer** [alan-cooney/knex-data-api-client#2]
Not sure if it's in this implementation or @jeremydaly, but when I issue bad queries (or good queries fail for some reason) I'm only getting 'timeout errors' from Bluebird and not the error itself.

Example:
let result = knex.raw('show blablbalbalbal;')
console.log(result)
```
TimeoutError: timeout error
    at SubError (/Users/amirbenari/CodeProjects/Silo/metadata-service/node_modules/bluebird/js/release/errors.js:10:49)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

**Comment by alan-cooney** [comment]
Thanks @benariamir - I haven't added explicit support for knex.raw() so it's probably an issue on this side.

The problem with  knex.raw() is that not all sql commands are supported by the Data API, so a better fix may be to remove the functionality entirely. What do you think?

Feel free to submit a pull request by the way, if you want to make some changes here.

**Comment by TheMonkWhoSoldHisServer** [comment]
I don't thing its related to knex.raw function, it was just an example.
The following is giving same result:

let fields = await knex.schema.hasColumn('NOTEXISTS');
console.log(fields);
```
TimeoutError: timeout error
    at SubError (/Users/amirbenari/CodeProjects/Silo/metadata-service/node_modules/bluebird/js/release/errors.js:10:49)
    at processTicksAndRejections (internal/process/next_tick.js:81:5)
```

I'll try to debug it and see if it's something I can fix.

**Comment by TheMonkWhoSoldHisServer** [comment]
I don't think it has anything to do with your implementation.. the debugging takes me all the way to Knex.js and couldn't find the source if this issue.

I did however to code around this:
```
    constructor(knex) {
        this._knex = knex;
    }

    _describeTable(tableName) {
        return this._tryExecute(this._knex.schema.hasColumn(tableName));
    }

    async _tryExecute(knexFunction) {
        return new Promise(async (resolve, reject) => {
            this._knex.on('query-error', (error, obj)=> {
                reject(error);
            });
            let result = await knexFunction;
            return resolve(result);
        });
    }
```

**Comment by alan-cooney** [comment]
Hi @benariamir - I believe this is fixed in the latest commit. Turned out to be an issue with incompatibilities between Bluebird and native Promises. Give it a try and I'll publish the latest version after a little more testing.

**Comment by alan-cooney** [comment]
Marking as fixed - this is now working on our live CI

**Comment by TheMonkWhoSoldHisServer** [comment]
@alan-cooney works good! thanks!
