### ISSUE TITLE
Support for postgres knex dialect

### ISSUE THREAD

**Issue by cbumstead** [alan-cooney/knex-data-api-client#3]
It would be great to have support for postgres as well as mysql.

**Comment by alan-cooney** [comment]
Hi @cbumstead - agreed, but unfortunately we don't have time to add this at the moment. Are you interested in adding support for this?

**Comment by alan-cooney** [comment]
I've looked into this - it seems like the errors are likely to be straightforward to fix. They're from processResponse() formatting the response to look like the standard mysql/mysql2 driver, so these can just be over-ridden or removed for postgres.

Happy to help debug issues, but I'll still need another maintainer to solve this so closing for now.
